# Generated by Django 5.0.6 on 2024-05-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_zip_code_prefix', models.CharField(max_length=20)),
                ('customer_city', models.CharField(max_length=255)),
                ('customer_state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_zip_code_prefix', models.CharField(max_length=20)),
                ('geolocation_lat', models.FloatField()),
                ('geolocation_lng', models.FloatField()),
                ('geolocation_city', models.CharField(max_length=255)),
                ('geolocation_state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=255)),
                ('product_name_length', models.IntegerField()),
                ('product_description_length', models.IntegerField()),
                ('product_photos_qty', models.IntegerField()),
                ('product_weight_g', models.FloatField()),
                ('product_length_cm', models.FloatField()),
                ('product_height_cm', models.FloatField()),
                ('product_width_cm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_zip_code_prefix', models.CharField(max_length=20)),
                ('seller_city', models.CharField(max_length=255)),
                ('seller_state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=255)),
                ('order_purchase_timestamp', models.DateTimeField()),
                ('order_approved_at', models.DateTimeField()),
                ('order_delivered_carrier_date', models.DateTimeField()),
                ('order_delivered_customer_date', models.DateTimeField()),
                ('order_estimated_delivery_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('order_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_sequential', models.IntegerField()),
                ('payment_type', models.CharField(max_length=255)),
                ('payment_installments', models.IntegerField()),
                ('payment_value', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_score', models.IntegerField()),
                ('review_comment_title', models.CharField(max_length=255)),
                ('review_comment_message', models.TextField()),
                ('review_creation_date', models.DateTimeField()),
                ('review_answer_timestamp', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_limit_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('freight_value', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_amt', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.customer')),
            ],
        ),
    ]
