# Generated by Django 5.0.6 on 2024-05-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field_name', models.CharField(max_length=200)),
                ('int_field_name', models.IntegerField()),
            ],
        ),
    ]
